output_frame : output
source_frame : camera_depth_optical_frame
set_xfilter : false
set_yfilter : false
set_zfilter : false
filter_xmin : -5.0
filter_xmax : 5.0
filter_ymin : -5.0
filter_ymax : 5.0
filter_zmin : 0.3
filter_zmax : 1.0